### ISSUE TITLE
Text comparison running tool

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#60]
- [x] content integrity will provide a test script to execute a set of files from any pre-defined directory structure for text and metadata comparison
- [x] the test tool will provide usable results in the form of json, each file should processed will have a report of text and metadata comparison results, differences, difference percentages and basic file information

**Comment by MaNe2020** [comment]
@gmuditdce what is the difference between this work and the one done here: https://github.com/filetrust/cdr-content-integrity/blob/develop/docs/visual_comparison_test_runner.md

**Comment by gmuditdce** [comment]
@MaNe2020 
the description of this issue has a minor mistake.
This is a "Text comparison running tool" that was developed as part of this to compare any number of files for textual differences at one go using the /api/v1/compare endpoint. (@chrisdiao please change test to text in the description i am unable to do that )

https://github.com/filetrust/cdr-content-integrity/blob/develop/docs/visual_comparison_test_runner.md - This was another tool that was developed to do visual comparison of multiple files at one go with gw-vlc-visualiser. (using puppeteer ui-automation)

**Comment by MaNe2020** [comment]
@chrisdiao @gmuditdce we can move this issue for Release but this has a lots of issues.

Below error I was struggling
![image](https://user-images.githubusercontent.com/70108899/124998046-ff942500-e04b-11eb-85eb-1370f7e228e9.png)
got resolved by running ` npm install form-data --force`

this means there is some issue in package.json as form-data is not handled correctly

After this files started to get compared but if process is interrupted (stopped) and on ubuntu even from start I am seeing 
![image](https://user-images.githubusercontent.com/70108899/124998197-47b34780-e04c-11eb-9641-7248ba210feb.png)

I just had one brief moment where this was working.

Current directory structure is pretty misleading and I do not think this should be placed in tests/runner...
Also README needs to be updated:
- `.env` details should be explained because it is not clear if results/output folder gets automatically created
- This should be rephrased `Copy the package.json and compare.js scripts to some directory`
- Example of folder structure should be added
- Above err and fix should be added


@chrisdiao @gmuditdce pls create issues for rework that is needed based on above comments.
- Updating README
- Troubleshooting `Error: connect ECONNREFUSED 127.0.0.1:8080`
- Cleaning folder structure

**Comment by chrisdiao** [comment]
Included in v0.2.0 release
